apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-rule
  annotations:
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
